apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: umeshgayashan/auth-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: mysql+pymysql://auth_user:YourUserPassword@auth-mysql:3306/auth_db
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: auth-service
