apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: umeshgayashan/hotel-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: mysql+pymysql://hotel_user:YourUserPassword@hotel-mysql:3306/hotel_db
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: hotel-service
