apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-mysql
spec:
  selector:
    matchLabels:
      app: payment-mysql
  serviceName: "payment-mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-mysql
    spec:
      containers:
      - name: payment-mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payment-mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: payment_db
        - name: MYSQL_USER
          value: payment_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payment-mysql-secret
              key: user-password
        volumeMounts:
        - name: payment-mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: payment-mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: payment-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app: payment-mysql
